name: ArqoLagfix
version: 1.0-FULL
main: com.arqonara.arqolagfix.ArqoLagfix
api-version: '1.21'
author: Arqonara
description: Advanced lag prevention and server optimization

commands:
  arqolagfix:
    description: Main command for ArqoLagfix
    aliases: [alf, lagfix]
    usage: /<command> [subcommand]
    permission: arqolagfix.use

permissions:
  arqolagfix.use:
    description: Use basic commands
    default: true
  arqolagfix.admin:
    description: Use admin commands
    default: op
